#include "ReceiverConfig.h"

#include <QFile>
#include <QTextStream>

static QString trimmed(const QString &s) { return s.trimmed(); }

static bool parseKeyValue(const QString &line, QString *key, QString *value) {
  const int eq = line.indexOf('=');
  if (eq < 0) return false;
  if (key) *key = trimmed(line.left(eq));
  if (value) *value = trimmed(line.mid(eq + 1));
  return true;
}

static bool isCommentOrEmpty(const QString &line) {
  const QString t = trimmed(line);
  return t.isEmpty() || t.startsWith('#');
}

bool ReceiverConfigIo::loadFromFile(const QString &path, ReceiverConfig *out, QString *error) {
  if (!out) {
    if (error) *error = "internal: out is null";
    return false;
  }

  QFile f(path);
  if (!f.open(QIODevice::ReadOnly | QIODevice::Text)) {
    if (error) *error = QString("无法打开配置文件：%1").arg(path);
    return false;
  }

  ReceiverConfig cfg;
  QTextStream in(&f);
  int lineNo = 0;
  while (!in.atEnd()) {
    lineNo++;
    const QString raw = in.readLine();
    if (isCommentOrEmpty(raw)) continue;
    QString key, value;
    if (!parseKeyValue(raw, &key, &value)) {
      if (error) *error = QString("配置文件第%1行格式错误").arg(lineNo);
      return false;
    }
    if (key.compare("interface", Qt::CaseInsensitive) == 0) {
      cfg.interface = value;
    } else if (key.compare("port", Qt::CaseInsensitive) == 0) {
      cfg.port = value.toInt();
    }
  }

  if (cfg.interface.isEmpty()) {
    if (error) *error = "interface 不能为空";
    return false;
  }
  if (cfg.port <= 0 || cfg.port > 65535) {
    if (error) *error = "port 范围应为 1..65535";
    return false;
  }

  *out = cfg;
  return true;
}

bool ReceiverConfigIo::saveToFile(const QString &path, const ReceiverConfig &cfg, QString *error) {
  if (cfg.interface.isEmpty()) {
    if (error) *error = "interface 不能为空";
    return false;
  }
  if (cfg.port <= 0 || cfg.port > 65535) {
    if (error) *error = "port 范围应为 1..65535";
    return false;
  }

  const QString tmpPath = path + ".tmp";
  QFile f(tmpPath);
  if (!f.open(QIODevice::WriteOnly | QIODevice::Text | QIODevice::Truncate)) {
    if (error) *error = QString("无法写入配置文件：%1").arg(path);
    return false;
  }

  QTextStream out(&f);
  out << "# Auto-generated by TSN_SoftWare\n";
  out << "interface=" << cfg.interface << "\n";
  out << "port=" << cfg.port << "\n";
  f.close();

  QFile::remove(path);
  if (!QFile::rename(tmpPath, path)) {
    QFile::remove(tmpPath);
    if (error) *error = QString("保存失败：无法替换文件 %1").arg(path);
    return false;
  }
  return true;
}

