[global]
time_stamping           hardware
twoStepFlag             1
network_transport       L2
domainNumber            0
priority1               1
priority2               128
utc_offset 37
logSyncInterval         0
logAnnounceInterval     0
logMinDelayReqInterval  0
